services:
  # Provides a centralized infrastructure and set of APIs for building distributed systems.
  # ZooKeeper is suitable for coordinating distributed applications across large clusters of machines.
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      # ZOOKEEPER_TICK_TIME parameter defines the duration of each tick
      # A common default value is 2000 milliseconds (2 seconds).
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # Specifies the name of the listener used for communication between Kafka brokers
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # Provides a mapping between listener names and advertised addresses
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      # Specifies the default replication factor for topics created automatically by Kafka
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      # Specifies the replication factor for the internal Kafka topic used to store consumer offsets
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Specifies the default number of partitions for topics created automatically by Kafka
      KAFKA_NUM_PARTITIONS: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
